# Generated by Django 5.1.1 on 2024-09-21 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('border', '0003_alter_bordercheck_vehicle_alter_licenseplate_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorControlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='border.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='PlateRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='border.vehicle')),
            ],
        ),
    ]
