# Generated by Django 5.1.1 on 2024-09-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platerecognition',
            name='is_successful',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
