# Generated by Django 5.1.1 on 2024-09-09 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_color', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=100)),
                ('country_of_origin', models.CharField(max_length=50)),
                ('destination_country', models.CharField(max_length=50)),
                ('vehicle_photo', models.ImageField(blank=True, null=True, upload_to='vehicle_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='LicensePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate_number', models.CharField(max_length=20)),
                ('license_plate_image', models.ImageField(blank=True, null=True, upload_to='license_plates/')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('issued_at', models.DateField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='border.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='BorderCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('border_name', models.CharField(max_length=100)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('authorization_file', models.FileField(blank=True, null=True, upload_to='authorization_docs/')),
                ('is_approved', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='border.vehicle')),
            ],
        ),
    ]
