# Generated by Django 5.1.1 on 2024-09-21 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0002_remove_licenseplate_plate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordercheck',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='border_checks', to='border.vehicle'),
        ),
        migrations.AlterField(
            model_name='licenseplate',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_plates', to='border.vehicle'),
        ),
    ]
